      
version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  dateapp:
    image: dateapp
    build: 
      context: .
      dockerfile: MicroServices/DateApp/DateApp.Application/Dockerfile
    container_name: dateapp-container
    ports:
      - "7141:80"
    environment: 
       - RABBIT_HOSTNAME=rabbitmq
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  identityserver:
    image: identityserver
    environment: 
       - RABBIT_HOSTNAME=rabbitmq
    container_name: identityserver-container
    ports:
      - "7096:80"
    build: 
      context: .
      dockerfile: MicroServices/IdentityServer/IdentityServer.Application/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
  



  