global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Text;
global using MediatR;
global using Microsoft.AspNetCore.Identity;
global using Domain.Entities;
global using System.Security.Claims;
// global using Server.Models;
global using Application.DTOs;
global using Application.Functions.UserFunctions.Queries;
// global using Server.Services.Interface;
global using Microsoft.AspNetCore.Authorization;
global using Application.Services;
global using Application.Interfaces.Services;
global using AutoMapper;
global using Application.Pagination;
global using Shared.Abstraction.Extensions;
global using  IdentityServer.Application.Services.Interfaces;