// <auto-generated />
using System;
using App.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221227132314_Migrate")]
    partial class Migrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.UserComment", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComment"));

                    b.Property<int?>("CommentedByUserUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentedToUserUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComment");

                    b.HasIndex("CommentedByUserUserId");

                    b.HasIndex("CommentedToUserUserId");

                    b.ToTable("UserComments");
                });

            modelBuilder.Entity("Api.Entities.UserLike", b =>
                {
                    b.Property<int>("UserIdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserIdLike"));

                    b.Property<int?>("LikedByUserUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LikedToUserUserId")
                        .HasColumnType("int");

                    b.HasKey("UserIdLike");

                    b.HasIndex("LikedByUserUserId");

                    b.HasIndex("LikedToUserUserId");

                    b.ToTable("UserLikes");
                });

            modelBuilder.Entity("Api.Entities.UserPost", b =>
                {
                    b.Property<int>("UserPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPostId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromUserUserId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserPostId");

                    b.HasIndex("FromUserUserId");

                    b.ToTable("UserPosts");
                });

            modelBuilder.Entity("Api.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Api.Entities.UserComment", b =>
                {
                    b.HasOne("Api.Entities.UserProfile", "CommentedByUser")
                        .WithMany("CommentsByUsers")
                        .HasForeignKey("CommentedByUserUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Entities.UserProfile", "CommentedToUser")
                        .WithMany("CommentsFromAnotherUsers")
                        .HasForeignKey("CommentedToUserUserId");

                    b.Navigation("CommentedByUser");

                    b.Navigation("CommentedToUser");
                });

            modelBuilder.Entity("Api.Entities.UserLike", b =>
                {
                    b.HasOne("Api.Entities.UserProfile", "LikedByUser")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("LikedByUserUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Entities.UserProfile", "LikedToUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedToUserUserId");

                    b.Navigation("LikedByUser");

                    b.Navigation("LikedToUser");
                });

            modelBuilder.Entity("Api.Entities.UserPost", b =>
                {
                    b.HasOne("Api.Entities.UserProfile", "FromUser")
                        .WithMany("PostsUser")
                        .HasForeignKey("FromUserUserId");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("Api.Entities.UserProfile", b =>
                {
                    b.Navigation("CommentsByUsers");

                    b.Navigation("CommentsFromAnotherUsers");

                    b.Navigation("LikedByUsers");

                    b.Navigation("LikedUsers");

                    b.Navigation("PostsUser");
                });
#pragma warning restore 612, 618
        }
    }
}
